"""Domain models and enums for valid-action.

All enums and Pydantic v2 models per spec section 6. IDs are opaque stable
strings generated by the generator (see generator._stable_id).
"""

from __future__ import annotations

import re
from datetime import date
from decimal import Decimal
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

# ---------- Enums (spec section 6.1) ----------


class Difficulty(str, Enum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"


class ActionType(str, Enum):
    MATERIAL_CONTRACT = "material_contract"
    EQUITY_GRANT = "equity_grant"
    SECURITY_ISSUANCE = "security_issuance"
    RELATED_PARTY_TRANSACTION = "related_party_transaction"
    TOKEN_TREASURY_TRANSACTION = "token_treasury_transaction"
    SUBSIDIARY_FINANCING = "subsidiary_financing"


class RecordType(str, Enum):
    SYNTHETIC_CODE = "synthetic_code"
    CHARTER = "charter"
    BYLAWS = "bylaws"
    COMMITTEE_CHARTER = "committee_charter"
    DELEGATION_MATRIX = "delegation_matrix"
    EQUITY_PLAN = "equity_plan"
    INVESTOR_AGREEMENT = "investor_agreement"
    DEBT_INSTRUMENT = "debt_instrument"
    PRIOR_RESOLUTION = "prior_resolution"
    INCUMBENCY = "incumbency"
    CONFLICT_DISCLOSURE = "conflict_disclosure"
    TRANSACTION_SUMMARY = "transaction_summary"


class BodyType(str, Enum):
    BOARD = "board"
    COMMITTEE = "committee"
    STOCKHOLDERS = "stockholders"
    SECURITY_CLASS = "security_class"
    OFFICER = "officer"
    THIRD_PARTY = "third_party"


class ApprovalMethod(str, Enum):
    MEETING = "meeting"
    WRITTEN_CONSENT = "written_consent"
    DELEGATED_APPROVAL = "delegated_approval"
    CONTRACTUAL_CONSENT = "contractual_consent"


class DefectCode(str, Enum):
    NO_ACTION = "no_action"
    WRONG_ENTITY = "wrong_entity"
    TERMS_MISMATCH = "terms_mismatch"
    CAPACITY_EXCEEDED = "capacity_exceeded"
    PROHIBITED_ACTION = "prohibited_action"
    MISSING_AUTHORIZATION = "missing_authorization"
    WRONG_AUTHORIZER = "wrong_authorizer"
    METHOD_NOT_PERMITTED = "method_not_permitted"
    NO_QUORUM = "no_quorum"
    INSUFFICIENT_VOTE = "insufficient_vote"
    INELIGIBLE_PARTICIPANT = "ineligible_participant"
    CONFLICT_NOT_DISCLOSED = "conflict_not_disclosed"
    CONFLICTED_VOTE_COUNTED = "conflicted_vote_counted"
    MISSING_RECUSAL = "missing_recusal"
    MISSING_CLASS_VOTE = "missing_class_vote"
    MISSING_CONSENT = "missing_consent"
    SEQUENCE_VIOLATION = "sequence_violation"
    STALE_AUTHORIZATION = "stale_authorization"
    INVALID_SIGNATORY = "invalid_signatory"
    EXECUTION_DATE_INVALID = "execution_date_invalid"
    SUPERSEDED_SOURCE = "superseded_source"
    DUPLICATE_EXECUTION = "duplicate_execution"


# ---------- Helpers ----------


_ID_PATTERN = re.compile(r"^[a-z][a-z0-9_]{2,63}$")


def _id_ok(value: str) -> bool:
    return bool(_ID_PATTERN.match(value))


def _positive_int(value: int) -> int:
    if value <= 0:
        raise ValueError(f"value must be positive, got {value}")
    return value


def _non_negative_int(value: int) -> int:
    if value < 0:
        raise ValueError(f"value must be non-negative, got {value}")
    return value


def _non_negative_decimal(value: Decimal) -> Decimal:
    if value < 0:
        raise ValueError(f"value must be non-negative, got {value}")
    return value


def _date_range(effective_from: date, effective_until: date | None) -> date | None:
    if effective_until is not None and effective_until < effective_from:
        raise ValueError("effective_until precedes effective_from")
    return effective_until


# ---------- Base ----------


class _StrictModel(BaseModel):
    """Default to forbid extra fields so generator bugs surface immediately."""

    model_config = ConfigDict(extra="forbid", validate_assignment=True)


# ---------- Entity / actor models (spec section 6.2) ----------


class Entity(_StrictModel):
    entity_id: str
    legal_name: str
    entity_type: Literal["corporation", "subsidiary"]
    parent_entity_id: str | None = None
    jurisdiction: str = "Northstar"
    formation_date: date

    @field_validator("entity_id")
    @classmethod
    def _check_entity_id(cls, value: str) -> str:
        if not _id_ok(value):
            raise ValueError(f"entity_id must match {_ID_PATTERN.pattern}")
        return value


class Person(_StrictModel):
    person_id: str
    display_name: str
    active_from: date
    active_until: date | None = None
    relationships: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def _check_active_range(self) -> "Person":
        _date_range(self.active_from, self.active_until)
        return self


class RoleAppointment(_StrictModel):
    role_id: str
    entity_id: str
    person_id: str
    role_type: Literal["director", "officer", "committee_member"]
    title: str
    body_id: str | None = None
    effective_from: date
    effective_until: date | None = None

    @model_validator(mode="after")
    def _check_range(self) -> "RoleAppointment":
        _date_range(self.effective_from, self.effective_until)
        return self


class GovernanceBody(_StrictModel):
    body_id: str
    entity_id: str
    body_type: BodyType
    display_name: str
    member_role_ids: list[str] = Field(default_factory=list)


# ---------- Ownership and capacity (spec section 6.3) ----------


class SecurityClass(_StrictModel):
    class_id: str
    entity_id: str
    name: str
    authorized: int
    issued: int = Field(ge=0)
    reserved: int = Field(ge=0)
    votes_per_unit: Decimal = Decimal("1")

    @model_validator(mode="after")
    def _check_authorized(self) -> "SecurityClass":
        if self.authorized <= 0:
            raise ValueError("authorized must be positive")
        if self.issued + self.reserved > self.authorized:
            raise ValueError("issued + reserved exceeds authorized")
        if self.votes_per_unit < 0:
            raise ValueError("votes_per_unit must be non-negative")
        return self

    @property
    def available(self) -> int:
        return self.authorized - self.issued - self.reserved


class HolderPosition(_StrictModel):
    holder_id: str
    class_id: str
    units: int = Field(ge=0)
    effective_from: date
    effective_until: date | None = None

    @model_validator(mode="after")
    def _check_range(self) -> "HolderPosition":
        _date_range(self.effective_from, self.effective_until)
        return self


class EquityPlanCapacity(_StrictModel):
    plan_id: str
    entity_id: str
    total_reserved: int
    granted: int = Field(ge=0)
    cancelled_returned: int = Field(ge=0)

    @model_validator(mode="after")
    def _check_capacity(self) -> "EquityPlanCapacity":
        if self.total_reserved <= 0:
            raise ValueError("total_reserved must be positive")
        if self.granted < 0 or self.cancelled_returned < 0:
            raise ValueError("granted and cancelled_returned must be non-negative")
        if self.granted > self.total_reserved + self.cancelled_returned:
            raise ValueError("granted exceeds total_reserved + cancelled_returned")
        return self

    @property
    def available(self) -> int:
        return self.total_reserved + self.cancelled_returned - self.granted


# ---------- Records (spec section 6.4) ----------


class RecordSection(_StrictModel):
    section_id: str
    heading: str
    text: str
    source_rule_ids: list[str] = Field(default_factory=list)


class LegalRecord(_StrictModel):
    record_id: str
    entity_id: str | None
    record_type: RecordType
    title: str
    effective_date: date
    supersedes_record_ids: list[str] = Field(default_factory=list)
    status: Literal["active", "superseded", "draft"] = "active"
    sections: list[RecordSection] = Field(default_factory=list)
    search_text: str = ""

    @model_validator(mode="after")
    def _check_unique_section_ids(self) -> "LegalRecord":
        seen: set[str] = set()
        for section in self.sections:
            if section.section_id in seen:
                raise ValueError(f"duplicate section_id {section.section_id}")
            seen.add(section.section_id)
        return self


# ---------- Action request and drafts (spec section 6.5) ----------


class BaseActionRequest(_StrictModel):
    request_id: str
    action_type: ActionType
    entity_id: str
    action_date: date
    business_purpose: str


class EquityGrantRequest(BaseActionRequest):
    action_type: Literal[ActionType.EQUITY_GRANT] = ActionType.EQUITY_GRANT
    recipient_person_id: str
    award_type: Literal["option", "restricted_stock", "rsu"]
    units: int
    vesting_months: int
    cliff_months: int
    strike_price: Decimal | None = None

    @field_validator("units", "vesting_months", "cliff_months")
    @classmethod
    def _positive(cls, value: int) -> int:
        return _positive_int(value)


class SecurityIssuanceRequest(BaseActionRequest):
    action_type: Literal[ActionType.SECURITY_ISSUANCE] = ActionType.SECURITY_ISSUANCE
    purchaser_id: str
    class_id: str
    units: int
    price_per_unit: Decimal
    financing_round: str

    @field_validator("units")
    @classmethod
    def _positive_units(cls, value: int) -> int:
        return _positive_int(value)

    @field_validator("price_per_unit")
    @classmethod
    def _non_negative_price(cls, value: Decimal) -> Decimal:
        return _non_negative_decimal(value)


class MaterialContractRequest(BaseActionRequest):
    action_type: Literal[ActionType.MATERIAL_CONTRACT] = ActionType.MATERIAL_CONTRACT
    counterparty_id: str
    contract_category: str
    total_commitment: Decimal
    term_months: int
    includes_exclusivity: bool = False
    includes_data_processing: bool = False

    @field_validator("total_commitment")
    @classmethod
    def _non_negative(cls, value: Decimal) -> Decimal:
        return _non_negative_decimal(value)

    @field_validator("term_months")
    @classmethod
    def _positive(cls, value: int) -> int:
        return _positive_int(value)


class RelatedPartyTransactionRequest(BaseActionRequest):
    action_type: Literal[ActionType.RELATED_PARTY_TRANSACTION] = ActionType.RELATED_PARTY_TRANSACTION
    counterparty_id: str
    related_person_id: str
    transaction_category: str
    total_value: Decimal

    @field_validator("total_value")
    @classmethod
    def _non_negative(cls, value: Decimal) -> Decimal:
        return _non_negative_decimal(value)


class TokenTreasuryTransactionRequest(BaseActionRequest):
    action_type: Literal[ActionType.TOKEN_TREASURY_TRANSACTION] = ActionType.TOKEN_TREASURY_TRANSACTION
    counterparty_id: str
    token_units: Decimal
    price_per_token: Decimal
    lockup_months: int
    related_person_id: str | None = None

    @field_validator("token_units", "price_per_token")
    @classmethod
    def _non_negative(cls, value: Decimal) -> Decimal:
        return _non_negative_decimal(value)

    @field_validator("lockup_months")
    @classmethod
    def _positive(cls, value: int) -> int:
        return _positive_int(value)


class SubsidiaryFinancingRequest(BaseActionRequest):
    action_type: Literal[ActionType.SUBSIDIARY_FINANCING] = ActionType.SUBSIDIARY_FINANCING
    subsidiary_id: str
    lender_id: str
    principal: Decimal
    maturity_months: int
    parent_guarantee: bool = False

    @field_validator("principal")
    @classmethod
    def _non_negative(cls, value: Decimal) -> Decimal:
        return _non_negative_decimal(value)

    @field_validator("maturity_months")
    @classmethod
    def _positive(cls, value: int) -> int:
        return _positive_int(value)


ActionRequest = (
    EquityGrantRequest
    | SecurityIssuanceRequest
    | MaterialContractRequest
    | RelatedPartyTransactionRequest
    | TokenTreasuryTransactionRequest
    | SubsidiaryFinancingRequest
)


def action_request_discriminator(value: ActionRequest | dict[str, Any]) -> str:
    """Return the action_type string of a request."""
    if isinstance(value, BaseModel):
        return value.action_type.value
    return value["action_type"]


# ---------- Authorization and execution (spec section 6.6) ----------


class AuthorizationAttempt(_StrictModel):
    attempt_id: str
    action_id: str
    authorizer_id: str
    method: ApprovalMethod
    participant_ids: list[str] = Field(default_factory=list)
    recused_ids: list[str] = Field(default_factory=list)
    disclosure_record_ids: list[str] = Field(default_factory=list)
    timestamp_step: int
    approved: bool
    defect_codes: list[DefectCode] = Field(default_factory=list)


class ExecutionAttempt(_StrictModel):
    execution_id: str
    action_id: str
    signatory_person_id: str
    timestamp_step: int
    valid: bool
    defect_codes: list[DefectCode] = Field(default_factory=list)


# ---------- Created action draft ----------


class CreatedAction(_StrictModel):
    """The immutable, agent-created draft action. Comparison against the
    request determines TERMS_MISMATCH (spec section 12.4)."""

    action_id: str
    request_id: str
    entity_id: str
    action_date: date
    payload: dict[str, Any]
    action_type: ActionType
    created_step: int


# ---------- Oracle solution ----------


class OracleAuthorizationStep(_StrictModel):
    requirement_id: str
    authorizer_id: str
    method: ApprovalMethod
    participant_ids: list[str]
    recused_ids: list[str] = Field(default_factory=list)
    disclosure_record_ids: list[str] = Field(default_factory=list)
    signatory_person_ids: list[str] = Field(default_factory=list)
    timestamp_step: int


class OracleSolution(_StrictModel):
    feasible: bool
    minimum_process_cost: int
    action_payload: dict[str, Any] = Field(default_factory=dict)
    authorization_steps: list[OracleAuthorizationStep] = Field(default_factory=list)
    signatory_person_ids: list[str] = Field(default_factory=list)
    requirement_path_ids: list[str] = Field(default_factory=list)


# ---------- World ----------


class ValidActionWorld(_StrictModel):
    schema_version: str = "valid-action.world.v1"
    world_template_id: str
    seed: int
    difficulty: Difficulty
    action_date: date
    entities: list[Entity]
    people: list[Person]
    roles: list[RoleAppointment]
    bodies: list[GovernanceBody]
    security_classes: list[SecurityClass] = Field(default_factory=list)
    holder_positions: list[HolderPosition] = Field(default_factory=list)
    plan_capacities: list[EquityPlanCapacity] = Field(default_factory=list)
    records: list[LegalRecord] = Field(default_factory=list)
    requirements: Any  # RequirementGraph; forward-declared to avoid import cycle
    action_request: ActionRequest = Field(discriminator="action_type")
    oracle_solution: OracleSolution

    @model_validator(mode="after")
    def _check_unique_ids(self) -> "ValidActionWorld":
        entity_ids = {e.entity_id for e in self.entities}
        person_ids = {p.person_id for p in self.people}
        body_ids = {b.body_id for b in self.bodies}
        role_ids = {r.role_id for r in self.roles}
        class_ids = {s.class_id for s in self.security_classes}
        plan_ids = {p.plan_id for p in self.plan_capacities}
        record_ids = {r.record_id for r in self.records}

        for role in self.roles:
            if role.entity_id not in entity_ids:
                raise ValueError(f"role {role.role_id} references unknown entity")
            if role.person_id not in person_ids:
                raise ValueError(f"role {role.role_id} references unknown person")
            if role.body_id is not None and role.body_id not in body_ids:
                raise ValueError(f"role {role.role_id} references unknown body")
        for body in self.bodies:
            if body.entity_id not in entity_ids:
                raise ValueError(f"body {body.body_id} references unknown entity")
            for member_role_id in body.member_role_ids:
                if member_role_id not in role_ids:
                    raise ValueError(
                        f"body {body.body_id} member {member_role_id} unknown"
                    )
        for security in self.security_classes:
            if security.entity_id not in entity_ids:
                raise ValueError(f"security {security.class_id} unknown entity")
        for holder in self.holder_positions:
            if holder.class_id not in class_ids:
                raise ValueError(f"holder {holder.holder_id} unknown class")
            if holder.holder_id not in entity_ids and holder.holder_id not in person_ids:
                raise ValueError(f"holder {holder.holder_id} must be entity or person")
        for plan in self.plan_capacities:
            if plan.entity_id not in entity_ids:
                raise ValueError(f"plan {plan.plan_id} unknown entity")
        for record in self.records:
            if record.entity_id is not None and record.entity_id not in entity_ids:
                raise ValueError(f"record {record.record_id} unknown entity")
            for superseded in record.supersedes_record_ids:
                if superseded not in record_ids:
                    raise ValueError(
                        f"record {record.record_id} supersedes unknown {superseded}"
                    )
        return self

    def record_by_id(self, record_id: str) -> LegalRecord | None:
        for r in self.records:
            if r.record_id == record_id:
                return r
        return None

    def entity_by_id(self, entity_id: str) -> Entity | None:
        for e in self.entities:
            if e.entity_id == entity_id:
                return e
        return None

    def body_by_id(self, body_id: str) -> GovernanceBody | None:
        for b in self.bodies:
            if b.body_id == body_id:
                return b
        return None

    def person_by_id(self, person_id: str) -> Person | None:
        for p in self.people:
            if p.person_id == person_id:
                return p
        return None

    def role_by_id(self, role_id: str) -> RoleAppointment | None:
        for r in self.roles:
            if r.role_id == role_id:
                return r
        return None


__all__ = [
    "ActionType",
    "ApprovalMethod",
    "BodyType",
    "DefectCode",
    "Difficulty",
    "RecordType",
    "ActionRequest",
    "AuthorizationAttempt",
    "BaseActionRequest",
    "CreatedAction",
    "Entity",
    "EquityGrantRequest",
    "EquityPlanCapacity",
    "ExecutionAttempt",
    "GovernanceBody",
    "HolderPosition",
    "LegalRecord",
    "MaterialContractRequest",
    "OracleAuthorizationStep",
    "OracleSolution",
    "Person",
    "RecordSection",
    "RelatedPartyTransactionRequest",
    "RoleAppointment",
    "SecurityClass",
    "SecurityIssuanceRequest",
    "SubsidiaryFinancingRequest",
    "TokenTreasuryTransactionRequest",
    "ValidActionWorld",
    "action_request_discriminator",
]
